import { readFile, writeFile, mkdir, access } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { constants } from 'node:fs'

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8')
const sites = [...html.matchAll(/\['([^']+)','(https:\/\/[^']+)',\d+,\d+\]/g)]
  .map(([, name, url]) => ({ name, url }))
  .filter((site, index, all) => all.findIndex(other => other.url === site.url) === index)
const root = new URL('../', import.meta.url)
const iconsDir = new URL('../icons/', import.meta.url)
await mkdir(iconsDir, { recursive: true })

const date = new Date().toISOString().slice(0, 10)
const status = {}
const icons = {}

function iconName(url) {
  return `${createHash('sha256').update(url).digest('hex').slice(0, 16)}.png`
}

async function check(site) {
  const controller = new AbortController()
  const timer = setTimeout(() => controller.abort(), 12000)
  try {
    const response = await fetch(site.url, {
      method: 'HEAD',
      redirect: 'follow',
      signal: controller.signal,
      headers: { 'user-agent': 'Open-Web-Atlas-Availability-Check/1.0' }
    })
    return response.status < 500 ? 'up' : 'issue'
  } catch {
    return 'unknown'
  } finally {
    clearTimeout(timer)
  }
}

async function downloadIcon(site) {
  const file = iconName(site.url)
  const output = new URL(`../icons/${file}`, import.meta.url)
  icons[site.url] = `icons/${file}`
  try {
    await access(output, constants.F_OK)
    return
  } catch {}
  try {
    const domain = new URL(site.url).hostname
    const response = await fetch(`https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=64`)
    if (!response.ok) return
    const bytes = new Uint8Array(await response.arrayBuffer())
    if (bytes.length > 100) await writeFile(output, bytes)
  } catch {}
}

for (let index = 0; index < sites.length; index += 10) {
  const batch = sites.slice(index, index + 10)
  await Promise.all(batch.map(async site => {
    status[site.url] = { state: await check(site), checked: date }
    await downloadIcon(site)
  }))
}

const output = `// Generated by scripts/refresh-assets.mjs\nwindow.SITE_STATUS=${JSON.stringify(status)};\nwindow.SITE_ICONS=${JSON.stringify(icons)};\n`
await writeFile(new URL('../status.js', import.meta.url), output)
console.log(`Checked ${sites.length} sites and prepared local icons.`)
